### ISSUE TITLE
请问about页面出现undefined如何解决？

### ISSUE THREAD

**Issue by xingweitian** [chunqiuyiyu/hexo-theme-polk#2]
您好！
我使用 hexo new page "about" 新建了about文件夹和index.md文件
但是about页面的标题是undefined，请问如何解决？

**Comment by chunqiuyiyu** [comment]
修改 about 文件夹中的 index.md 文件，在头部声明处将 title 填好即可。

**Comment by xingweitian** [comment]
问题解决，谢谢您！
