### ISSUE TITLE
Syntax highlighting doesn't seem to be working...

### ISSUE THREAD

**Issue by mkpt** [chunqiuyiyu/hexo-theme-polk#3]
Hello! When I tag my code sample as "js" the highlighting doesn't work.

The code:

![](https://i.imgur.com/MmmvVbY.png)

The settings:

![](https://i.imgur.com/DNYc8lf.png)

I haven't touched the code in `post.syl`:

![](https://i.imgur.com/UTw1z6w.png)

The output:

![](https://i.imgur.com/SmFdDxU.png)

Is there anything else I need to configure?

**Comment by chunqiuyiyu** [comment]
It's my fault.Now I already have updated the theme highlighting code.You can update the repo.
