### ISSUE TITLE
如何添加新的分类?

### ISSUE THREAD

**Issue by leviathan0992** [chunqiuyiyu/hexo-theme-polk#9]
@chunqiuyiyu  我现在在使用你的模板，想再添加一项类似于archive的标签，如何添加?

**Comment by chunqiuyiyu** [comment]
@Leviathan1995 不太明白你的意思，你是要添加分类功能还是名为 archive 的新页面？分类功能不支持，你可以参照其他主题改一下，新页面需要你新建 MD 文件，参考这个问题 #8 。
